### PR TITLE
kiwix local server port can be set at the constructor

### PR DESCRIPTION
**Pull request by jetownfeve21**

### CODE REVIEW

**Comment by mgautierfr** [comment]
I would prefer to add the port as argument (at creation).
This way, we make the kiwixServe configurable and we will have nothing to change on kiwix-lib side when we will have the port configurable in kiwix-desktop.

**Comment by jetownfeve21** [comment]
at creation it means the constructor or the run() method ?

**Comment by mgautierfr** [comment]
In the constructor.

**Comment by mgautierfr** [comment]
I prefer to not change the return value of `run`. The port is already known (it is passed at creation) and I prefer to keep the return value to some potential future more useful information.

**Comment by mgautierfr** [comment]
And add a default value for the port in the constructor. This way we don't break the API.

**Pull request merged**
