### PR TITLE
Implement Open Search in content

### PR DESCRIPTION
**Pull request by dledanseur**
Provides Open Search endpoints to search into content and retrieve results thanks to an Atom feed.

Fixes https://github.com/kiwix/kiwix-tools/issues/52

### CODE REVIEW

**Comment by kelson42** [comment]
@dledanseur Is the PR ready to be reviewed or is that a work in progress?

**Comment by dledanseur** [comment]
@kelson42 Yes it's ready

**Comment by kelson42** [comment]
@dledanseur Could you please rebase on master?

**Comment by kelson42** [comment]
@dledanseur This code should be also a bit automated tested. Would that be possible?

**Comment by dledanseur** [comment]
The code has been rebased. Regarding the tests, I cannot find any existing test covering the area on which I can base my work (or did I miss something ?). It seems to me a bit off-topic for this PR to decide of a whole test strategy...

**Comment by kelson42** [comment]
@dledanseur The unit tests are in the `test` directory. Run them with `ninja -C build test`.

**Comment by kelson42** [comment]
Superseeded by #299

**Pull request closed without merging**
