### PR TITLE
Replace buggy example.zim with a correct one

### LINKED ISSUE #467: Buggy test zim examples.zim should be replaced
Refer openzim/libzim#521
A test zim file [examples.zim](https://github.com/kiwix/kiwix-lib/blob/baed447dd38a29342a3f509151d6d274774e0a32/test/data/example.zim) is incorrectly written and should be replaced to avoid any future confusion.

### PR DESCRIPTION
**Pull request by maneeshpm**
Fixes #467 

The existing `example.zim` has an improper main page and hence an unusable
index. It is replaced with a fresh one.

### CODE REVIEW

**Comment by mgautierfr** [comment]
Can you describe in the commit message how you've generated the zim file ? What is changed compared to the existing one ?

Diff is almost impossible to do for binary files. So the commit message must be descriptive about what I've been done, how and why ?
(They should be all the time, but here it is even more important).

**Comment by maneeshpm** [comment]
@mgautierfr I have updated the commit description. Please let me know if I missed out on any info.

**Comment by mgautierfr** [comment]
Can you create a PR on https://github.com/openzim/zim-testing-suite with the source directory used to create the zim file ?

I suppose you've used the `master` branch of libzim/zim-tools ?

**Comment by maneeshpm** [comment]
@mgautierfr I have opened a pr there. Yes, I used the latest master of zim-tools.

**Comment by kelson42** [comment]
@maneeshpm Should we close this PR in favour of https://github.com/openzim/zim-testing-suite/pull/1 ?

**Comment by mgautierfr** [comment]
> Should we close this PR in favour of openzim/zim-testing-suite#1 ?

No. This Pr is adding (binary) zim file to kiwix-lib.
openzim/zim-testing-suite#1 is adding the source of the zim file to have a trace of how we generate this zim file (and potential recreate it).

**Comment by kelson42** [comment]
@mgautierfr OK, so can we merge this one?

**Pull request merged**
