### PR TITLE
update book even if the members aren't empty

### PR DESCRIPTION
**Pull request by jetownfeve21**
remove the conditions to always update the book

fix https://github.com/kiwix/kiwix-desktop/issues/300

### CODE REVIEW

**Comment by kelson42** [comment]
@jetownfeve21 I don't see any testing to avoid erasing by updating if a path is already there AND zim loaded properly. Normal?

**Comment by kelson42** [comment]
@jetownfeve21 I guess this should be reviewed by @mgautierfr!?

**Comment by mgautierfr** [comment]
From what I see in kiwix-desktop#300, we try to update the book (referenced by the bookId) but, as the path already exists it is not updated.

As far as I know, the update function was used only when moving from a library version to another. And when with the `add` action of kiwix-manage.

@kelson42 Your question is legit. And more globally it is what happens if we have two zim files (same id, two different paths) ?
I don't think there is a unique solution, it depends of the context and it should be handled on the caller side.

It seems to me that, on the library side, if a caller want to update a book in the library, we update it with the values given. I don't see a real reason to refuse a value update.
But I'm open to counter-arguments.

**Comment by kelson42** [comment]
@mgautierfr Agree. Different scenarios should be handled at a higher level. PR looks good to me.

**Comment by kelson42** [comment]
@mgautierfr Please review

**Pull request merged**
