### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by shahaab**

### CODE REVIEW

**Comment by kelson42** [comment]
@shahaab still a draft?

**Comment by shahaab** [comment]
> @shahaab still a draft?
       No, I have fixed it. Its ready for review.

**Review by kelson42 — APPROVED** [review]

**Comment by kelson42** [comment]
@shahaab Please remove the draft next time. You need as well to rebase this branch on origin/master.

**Comment by shahaab** [comment]
Okay

**Comment by mgautierfr** [comment]
Please rebase your branch on master. To not merge master into your branch.

**Comment by kelson42** [comment]
@shahaab You have write permission meanwhile on this repository. Please make your PR here (instead of in your fork). But you have to create a feature branch, don't work directly on master.

**Comment by kelson42** [comment]
Superseeded by https://github.com/kiwix/kiwix-lib/pull/453

**Pull request closed without merging**
