### PR TITLE
descending sort book

### PR DESCRIPTION
**Pull request by jetownfeve21**

### CODE REVIEW

**Comment by kelson42** [comment]
@jetownfeve21 @mgautierfr This branch is quite old and should be reviewed ASAP and if OK merged. I just have rebased it.

**Comment by mgautierfr** [comment]
This is pretty complex and with a lot of duplication.
There are two things here :
- The key we are using to sort the books
- The order we are using.

This is two different things and it should (and could) be handle separatly.
The Comparator could be extended with another template parameter for the order. And the template specitalization being used for implementing the order.

Something like that (not tested) :
```c++
template<supportedListSortBy sort, bool asc_order>
struct Comparator {
  Library* lib;
  Comparator(Library* lib) : lib(lib) {}

  bool operator() (const std::string& id1, const std::string& id2) {
    return get_keys(id1) < get_keys(id2);
  }

  template<typename KEYTYPE>
  bool compare(const KEYTYPE& a, const KEYTYPE& b);
  std::string get_keys(const std::string& id);
  unsigned int get_keyi(const std::string& id);
};
```

I always thing that the api of the listBookIds is pretty complex (too many arguments).
We may rewrite it later but it is not for now. To avoid to add a extra arguments to the functions, we could indeed extend the `supportedListSortBy` enum, but the implementation doesn't have to follow (and use) the same enum.

**Comment by mgautierfr** [comment]
This is an API change. And kiwix-tools (at least) use this api. Please provide a PR on kiwix-tools side to adapt to the new api (this is already done on kiwix-desktop side with kiwix/kiwix-desktop#142)

**Comment by mgautierfr** [comment]
I've just created a PR for a better API for library filtering and sorting here (https://github.com/kiwix/kiwix-lib/pull/234). I let you review this PR but I think it would be better to use the new API than extends the existing one.

**Pull request closed without merging**
