### PR TITLE
Fixes kiwix-android issue#765

### PR DESCRIPTION
**Pull request by Aditya-Sood**
- Contains changes to JNIKiwixReader for kiwix-android which fix issue [#765](https://github.com/kiwix/kiwix-android/issues/765)

- Since kiwix-build relies on using the master branch of the kiwix-lib source code, the PR for updated code of kiwix-android needs to use the same version of kiwix-lib as the one which has this PR merged

### CODE REVIEW

**Comment by kelson42** [comment]
This branch needs to be rebased

**Comment by Aditya-Sood** [comment]
@kelson42 I had merged with master yesterday before pushing
Do you want me to undo that and rebase instead?

**Comment by kelson42** [comment]
@Aditya-Sood Yes, the rules are not the same as on kiwix-android. Here the feature branches need to be rebased properly on master before review/merge. So never ever a merge from master in a feature branch on this repo... and in general in all repos (except kiwix-android).

**Comment by Aditya-Sood** [comment]
@kelson42 I've re-based the branch

**Comment by Aditya-Sood** [comment]
@kelson42 what is the expected date of the next kiwix-lib version release? I'll set a reminder for updating the complimentary kiwix-android PR accordingly

**Pull request merged**
